codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error
        only_pulls: true
        flags: frontend
