name: Backend Test

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        working-directory: ./back
        run: mvn clean install

      # Step 4: Run tests and generate Jacoco report
      - name: Run tests and generate Jacoco report
        working-directory: ./back
        run: mvn test jacoco:report

      # Step 5: Generate and check the code coverage report
      - name: JaCoCo Code Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: back/target/site/jacoco/jacoco.xml
          coverage_report_name: Back Spring Boot Tests
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 80
          fail_below_threshold: true