name: Frontend Test

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: ./front
        run: npm ci

      # Step 4: Run tests
      - name: Run tests
        working-directory: ./front
        run: npm run test

      # Step 5: Upload coverage to Codecov
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./front/coverage/lcov.info
          flags: frontend
          name: codecov-frontend-report

      - name: Check coverage
        run: |
          if ! grep -q "Statements   : 70%" ./coverage/report-html/index.html; then
            echo "Coverage threshold not met."
            exit 1
          fi

      # Step 6: Test Reporting
      - name: Test Reporting
        uses: phoenix-actions/test-reporting@v14
        if: always()
        with:
          name: Font Angular Tests
          path: 'front/test-results/*.xml'
          reporter: 'java-junit'
