name: SonarCloud analyze

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 1: Setup for all necessary tools
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 2: Build commands for backend and frontend
      - run: npm install && npm run build
        working-directory: ./front

      # Step 3: Run frontend tests
      - name: Run Frontend Tests
        run: npm test
        working-directory: ./front

      - name: List TypeScript Coverage Report
        run: ls -l coverage/
        working-directory: ./front

      - name: Display TypeScript Coverage Report Content
        run: cat front/coverage/lcov.info
        working-directory: ./

      # Step 4: SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
