name: SonarCloud analyze

# Triggers for the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 1: Setup for all necessary tools
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Step 2: Build commands for backend and frontend
      - run: mvn clean verify
        working-directory: ./back

      # Step 3: Run backend tests
      - name: Run Backend Tests
        run: mvn test
        working-directory: ./back

      - name: List Jacoco Coverage Report
        run: ls -l target/site/jacoco/
        working-directory: ./back

      - name: Display Jacoco Report Content
        run: cat back/target/site/jacoco/jacoco.xml
        working-directory: ./

       # Step 4: SonarCloud analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
